services:
  morphos-service:
    container_name: morphos
    image: ghcr.io/danvergara/morphos-server:latest
    network_mode: bridge
    ports:
      - 18080:8080
    volumes:
      - /tmp:/tmp
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 30s
