services:
  portainer-service:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    network_mode: bridge
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data:
    external: true
